1015 make default EvalCallback work for recurrent policies
hill-a/stable-baselines pull request #1017
Opened 2020-10-07 09:59 UTC by mily20001

Main purpose of this change is to make EvalCallback work also for recurrent policies trained on more than 1 environment, whose as for now requires the same observation space shape as during training stage

## Description
Depending on policy `recurrent` prop EvalCallback pads observations with zeros to make them compatible with training observation shape

## Motivation and Context
Closes #1015 
Implemented based on https://github.com/hill-a/stable-baselines/issues/166#issuecomment-502350843
- [x] I have raised an issue to propose this change ([required](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the [changelog](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/changelog.rst) accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have ensured `pytest` and `pytype` both pass (by running  `make pytest` and `make type`).

2020-10-07 20:30 UTC, Miffyli commented
I will let @araffin do the review, but meanwhile please add your username to the changelog as described in the contribution guide :).

2020-10-09 10:37 UTC, araffin requested changes
Minor edit needed, otherwise LGTM ;)

2020-10-09 10:37 UTC, araffin commented on stable_baselines/common/evaluation.py
> +            if is_recurrent:
missing comment (and maybe link to the issue)

2020-10-09 10:37 UTC, araffin commented on stable_baselines/common/evaluation.py
> +                obs, reward, done, _info = env.step(action)
```suggestion
            new_obs, reward, done, _info = env.step(action)
            if is_recurrent:
                obs[0, :] = new_obs
            else:
                obs = new_obs
```

2020-10-12 12:10 UTC, araffin approved these changes
LGTM, thanks =)

2020-10-12 12:10 UTC, merged